// <auto-generated />
using System;
using Lunia.V4.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lunia.V4.Infrastructure.Persistence.Migrations.Stage
{
    [DbContext(typeof(StageDbContext))]
    partial class StageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stage")
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lunia.V4.Domain.Entities.SquareStage", b =>
                {
                    b.Property<string>("ServerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("server_name");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer")
                        .HasColumnName("room_number");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("ConnectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("connection_count");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("SquareName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("square_name");

                    b.Property<int>("StageGroupHash")
                        .HasColumnType("integer")
                        .HasColumnName("stage_group_hash");

                    b.HasKey("ServerName", "RoomNumber")
                        .HasName("pk_square_stages");

                    b.ToTable("square_stages", "stage");

                    b.HasData(
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 0,
                            AccessLevel = 0,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Main Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 1,
                            AccessLevel = 11,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Myth Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 2,
                            AccessLevel = 12,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "PVP Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 3,
                            AccessLevel = 3,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Beginners Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 4,
                            AccessLevel = 2,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Slime Racing Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 5,
                            AccessLevel = 4,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 1 Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 6,
                            AccessLevel = 5,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 2 Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 7,
                            AccessLevel = 6,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 3 Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 8,
                            AccessLevel = 7,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 4 Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 9,
                            AccessLevel = 8,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 5 Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 10,
                            AccessLevel = 9,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 6 Square",
                            StageGroupHash = 53518598
                        },
                        new
                        {
                            ServerName = "Square Server",
                            RoomNumber = 11,
                            AccessLevel = 10,
                            Capacity = 70,
                            ConnectionCount = 0,
                            OrderNumber = 0,
                            SquareName = "Episode 7 Square",
                            StageGroupHash = 53518598
                        });
                });

            modelBuilder.Entity("Lunia.V4.Domain.Entities.StageServer", b =>
                {
                    b.Property<string>("ServerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("server_name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("address");

                    b.Property<int>("CongestionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("congestion_level");

                    b.Property<bool>("IsSquare")
                        .HasColumnType("boolean")
                        .HasColumnName("is_square");

                    b.Property<DateTimeOffset>("LastUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_up_at");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer")
                        .HasColumnName("room_count");

                    b.HasKey("ServerName")
                        .HasName("pk_stage_servers");

                    b.ToTable("stage_servers", "stage");

                    b.HasData(
                        new
                        {
                            ServerName = "Square Server",
                            Address = "192.168.0.30",
                            CongestionLevel = 0,
                            IsSquare = true,
                            LastUpAt = new DateTimeOffset(new DateTime(2021, 3, 18, 2, 20, 37, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Port = 15554,
                            RoomCount = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
